--SBR2K Hornmod 


HORNMOD_AddHorns({name = "sfx_hbdgku", info = "Oi, eu sou o Goku"},
{name = "sfx_hbdiri", info = "Irineu, voce nao sabe e nem eu"},
{name = "sfx_hbdlie", info = "Mentira. HAHAHAHAHAHA"},
{name = "sfx_hbdnau", info = "Pele - Nao"},
{name = "sfx_hbdnom", info = "Seu Madruga - NAO!"},
{name = "sfx_hbdnss", info = "n o s s a"},
{name = "sfx_hbdrlt", info = "Equipe rocket decolando na velocidade da luz"},
{name = "sfx_hbdrpr", info = "Equipe rocket partindo pra SEMPREE"},
{name = "sfx_hbdrpz", info = "rapaiz.mp4"},
{name = "sfx_hbdrtd", info = "Voce e retardado por acaso?"},
{name = "sfx_hbdsry", info = "SHIRIU AMIGO"},
{name = "sfx_hbdsts", info = "Sem seia"},
{name = "sfx_hbdtcl", info = "Ta cumendo ticolE"},
{name = "sfx_hbdtep", info = "Micheal Telo - Ai se eu te pego"},
{name = "sfx_hbdtmb", info = "Eu tambem"},
{name = "sfx_hbdtmm", info = "Todo mundo morreu, e acabo"},
{name = "sfx_hbdtrt", info = "Estou sentindo uma treta"},
{name = "sfx_hbdvij", info = "Qui viaji E essa vei"},
{name = "sfx_hbdxrp", info = "Esse cara e xarope"},
{name = "sfx_hbd100", info = "Jutsu secreto da aldeia da folha"},
{name = "sfx_hbd800", info = "E DE MAIS DE 8 MIL"},
{name = "sfx_hbdacl", info = "AGUA, COCA, LATAO (pa gringo e mais caro},"},
{name = "sfx_hbdaie", info = "Aaaaih"},
{name = "sfx_hbdamc", info = "AI MEU C*"},
{name = "sfx_hbdavn", info = "E verdade, quer dizer, as vezes nao"},
{name = "sfx_hbdbdg", info = "Bolina de gorfe"},
{name = "sfx_hbddcl", info = "Parece que a Equipe Rocket ta decolando denovoooooooo"},
{name = "sfx_hbddql", info = "NHAUMAUUM, daquele jeito"},
{name = "sfx_hbdero", info = "Erro"},
{name = "sfx_hbdfcs", info = "Fracassado"},
{name = "sfx_hbdfds", info = "fodase?"},
{name = "sfx_hbdflc", info = "Faliceu"}, -- Igual ao edit original do hornmod -- Fabiano 2020-08-11: é mesmo
{name = "sfx_hbdccr", info = "Churrasqueira Controle Remoto"},
{name = "sfx_hbddib", info = "EU SOU UM DIABO NECESSARIO"},
{name = "sfx_hbdela", info = "Ela Partiu"},
{name = "sfx_hbdgem", info = "Miseravel e um Genio"},
{name = "sfx_hbdpfb", info = "TA PEGANDO FOGO BIXO"},
{name = "sfx_hbdptv", info = "PUTA VIDA"},
{name = "sfx_hbdwoo", info = "VEGETAAA OLHA BEEEEEIM, WOOOOOOOOOOOOOOOOO"},
{name = "sfx_hbdrnd", info = "Ronaldinho Soccer"},
{name = "sfx_hbd7ms", info = "Descobridor dos 7 mares"},
{name = "sfx_hbdbol", info = "Risada do Bola"},
{name = "sfx_hbdcac", info = "Calma Cebolinha"},
{name = "sfx_hbdvdm", info = "Voce deve MORRE"},
{name = "sfx_hbdron", info = "Ronaldo"},
{name = "sfx_hbdqmr", info = "Que merda hein?"},
{name = "sfx_hbdpre", info = "PRERIGO"},
{name = "sfx_hbdmac", info = "OLHA O MACACO"},
{name = "sfx_hbdlcc", info = "Lagartixa com caibra"},
{name = "sfx_hbdjoj", info = "E te JooJ"},
{name = "sfx_hbdfl2", info = "Falou - Velberan"},
{name = "sfx_hbdfdp", info = "Teria sido melhor ir ver o filme do Pele"},
{name = "sfx_hbdeuu", info = "EU"},
{name = "sfx_hbdetl", info = "EU NAO TO LOUCO"},
{name = "sfx_hbdete", info = "E TETRA"},
{name = "sfx_hbdczb", info = "Risada do Cazalbe"},
{name = "sfx_hbdcao", info = "Volta o cao arrependido"},
{name = "sfx_hbdbrl", info = "BIRL"},
{name = "sfx_hbdbbn", info = "Ratinho Bobina"},
{name = "sfx_hbdast", info = "Nao contavam com a minha astucia"},
{name = "sfx_hbd37", info = "EEE PORR* E 37 ANOS C*RAi"},
{name = "sfx_hbdaah", info = "AAaaah, eu vo gozaaa"},
{name = "sfx_hbdmud", info = "MUDA MUDA MUDA MUDAAA"},
{name = "sfx_hbdprr", info = "ooooooooooooooooooo.....oooooh, porra"},
{name = "sfx_hbdflw", info = "eu vo ficando por aqui, NOS VEMOS NO PROXIMO VIDEO, falow"},
{name = "sfx_hbdshw", info = "HORA DO SHOW, porra"},
{name = "sfx_hbdora", info = "ORA ORA ORA ORA ORA ORA ORA ORAA"},
{name = "sfx_hbdono", info = "Knux, ono"},
{name = "sfx_hbdmlk", info = "Ajuda que o maluco ta doente"},
{name = "sfx_hbdchg", info = "CHEGA"},
{name = "sfx_hbdpze", info = "Poze fazendo oque ele faz de melhor"},
{name = "sfx_hbdcj", info = "Oh shit, here we go again"},
{name = "sfx_hbdban", info = "B A N I D O"},
{name = "sfx_hbdcu", info = "Manda um abraço pro meu tio Cuca Beludo"},
{name = "sfx_hbdnos", info = "Minha nossa nossa nossa"},
{name = "sfx_hbdngm", info = "Joao ninguem"},
{name = "sfx_hbdlan", info = "Ele rebateu de cabeca quando nao havia esperanca e foi um lance que"},
{name = "sfx_hbdcrl", info = "Oia ei ei ei uih. carai borracha"},
{name = "sfx_hbdspr", info = "PARA COM ESSA PORRA AE MERMAO"},
{name = "sfx_hbdavm", info = "ava eh memo"},
{name = "sfx_hbdpln", info = "Bomb has been planted"},
{name = "sfx_hbdcvl", info = "cavalo"},
{name = "sfx_hbdbur", info = "Ai que burro da zero pra ele"},
{name = "sfx_hbdchf", info = "Deixa os outro em paz"}, -- meu ex-chefe kkkk
{name = "sfx_hbdcoq", info = "coquinho"},
{name = "sfx_hbdbnn", info = "eh uma banana"},
{name = "sfx_hbdexc", info = "MGS Exclamation Point"},
{name = "sfx_hbdfb", info = "Facebook"},
{name = "sfx_hbdama", info = "amanco"},
{name = "sfx_hbdbr", info = "BRASIL sil sil"},
{name = "sfx_hbdhum", info = "Hum eh mesmo!"},
{name = "sfx_hbdzap", info = "WhatsApp"},
{name = "sfx_hbdbrh", info = "bruh"},
{name = "sfx_hbdpei", info = "peido"},
{name = "sfx_hbdqq", info = " Que que isso rapaz"},
{name = "sfx_hbdpel", info = "risada do peludao (atumalaca)"},
{name = "sfx_hbdstm", info = "Steam"},
{name = "sfx_hbdtrm", info = "trombone"},
{name = "sfx_hbduep", info = "UEPA!!!"},
{name = "sfx_hbdvai", info = "Vai ganhar ou nao vai"},
{name = "sfx_hbdchr", info = "Rochelle - CHRIIIIIIIIS"},
{name = "sfx_hbdmar", info = "Mario Games rindo"},
{name = "sfx_hbdbly", info = "BLYAT"},
{name = "sfx_hbd402", info = "4002-8922", extags = "yudi"},
{name = "sfx_hbdaee", info = "AEE KASINAO"}, -- lendário
{name = "sfx_hbdarr", info = "Arrego"},
{name = "sfx_hbdcgo", info = "CANT GET OVER, VAI DJ!"},
{name = "sfx_hbdcsb", info = "CALA A SUA BOCA"},
{name = "sfx_hbdcvs", info = "Chaves Chorando", extags = "pipipi"},
{name = "sfx_hbdhih", info = "Quico hihihi"},
{name = "sfx_hbdiba", info = "Ibagens com o comandante habilton", extags = "datena"},
{name = "sfx_hbdltc", info = "Lasier tomando choque", extags = "aiaaaaai"}, -- clássico
{name = "sfx_hbdmdc", info = "ME DA MEU CHIP PEDRO"},
{name = "sfx_hbdmer", info = "Fiquei na merda", extags = "Mamonas"},
{name = "sfx_hbdmnp", info = "Dona desse monumental par de coxas", extags = "marcio"},
{name = "sfx_hbdmu1", info = "Isso ai!", extags = "mineirinho"},
{name = "sfx_hbdsbc", info = "E Sabadaco"},
{name = "sfx_hbdsii", info = "Sanduiche-iche", extags = "ruth lemos"},
{name = "sfx_hbdvcb", info = "Vai comecar a baixaria", extags = "mamonas"},
{name = "sfx_hbdvlb", info = "Vira lata sofrendo de bronquite", extags = "quico"},
{name = "sfx_hbdvvp", info = "VOCE E A VERGONHA DA PROFISSION", extags = "pe de fava"},
{name = "sfx_hbdvvm", info = "Eu vim ver o macaco", extags = "Kaiba"} -- Segundo horn com macaco já
)


HORNMOD_AddHellHorns({name = "sfx_hbdaaa", info = "MAMAAAAAAAAAAAAAAAAAE"},
{name = "sfx_hbdbar", info = "Seu Barriga Demonio"},
{name = "sfx_hbdbdf", info = "Bau da Felicidade"},
{name = "sfx_hbdkns", info = "KASINAO NO SABADACO"}, -- a musica inteirinha
{name = "sfx_hbdmdj", info = "Sampley de guitarra"},
{name = "sfx_hbdmm0", info = "Monumental par de coxas completo"},
{name = "sfx_hbdpbt", info = "Pao de batataaa"},
{name = "sfx_hbdplg", info = "Plantao da Globo"},
{name = "sfx_hbdrsr", info = "1 minuto de risadas do Chaves"},
{name = "sfx_hbdsba", info = "Sabao cra cra"},
{name = "sfx_hbdvoa", info = "La vem o alemao - intro"}, -- seila
{name = "sfx_hbdaah", info = "AAaaah, eu vo gozaaa"},
{name = "sfx_hbdbbn", info = "Ratinho Bobina"}
)
