--SBR2K Hornmod 


HORNMOD_AddHorns({name = "sfx_hbdgku", info = "Oi, eu sou o Goku"},
{name = "sfx_hbdiri", info = "Irineu, voce nao sabe e nem eu"},
{name = "sfx_hbdlie", info = "Mentira. HAHAHAHAHAHA"},
{name = "sfx_hbdnau", info = "Pele - Nao"},
{name = "sfx_hbdnom", info = "Seu Madruga - NAO!"},
{name = "sfx_hbdnss", info = "n o s s a"},
{name = "sfx_hbdrlt", info = "Equipe rocket decolando na velocidade da luz"},
{name = "sfx_hbdrpr", info = "Equipe rocket partindo pra SEMPREE"},
{name = "sfx_hbdrpz", info = "rapaiz.mp4"},
{name = "sfx_hbdrtd", info = "Voce e retardado por acaso?"},
{name = "sfx_hbdsry", info = "SHIRIU AMIGO"},
{name = "sfx_hbdsts", info = "Sem seia"},
{name = "sfx_hbdtcl", info = "Ta cumendo ticolE"},
{name = "sfx_hbdtep", info = "Micheal Telo - Ai se eu te pego"},
{name = "sfx_hbdtmb", info = "Eu tambem"},
{name = "sfx_hbdtmm", info = "Todo mundo morreu, e acabo"},
{name = "sfx_hbdtrt", info = "Estou sentindo uma treta"},
{name = "sfx_hbdvij", info = "Qui viaji E essa vei"},
{name = "sfx_hbdxrp", info = "Esse cara e xarope"},
{name = "sfx_hbd100", info = "Jutsu secreto da aldeia da folha"},
{name = "sfx_hbd800", info = "E DE MAIS DE 8 MIL"},
{name = "sfx_hbdacl", info = "AGUA, COCA, LATAO (pa gringo e mais caro},"},
{name = "sfx_hbdaie", info = "Aaaaih"},
{name = "sfx_hbdamc", info = "AI MEU C*"},
{name = "sfx_hbdavn", info = "E verdade, quer dizer, as vezes nao"},
{name = "sfx_hbdbdg", info = "Bolina de gorfe"},
{name = "sfx_hbddcl", info = "Parece que a Equipe Rocket ta decolando denovoooooooo"},
{name = "sfx_hbddql", info = "NHAUMAUUM, daquele jeito"},
{name = "sfx_hbdero", info = "Erro"},
{name = "sfx_hbdfcs", info = "Fracassado"},
{name = "sfx_hbdfds", info = "fodase?"},
{name = "sfx_hbdflc", info = "Faliceu"}, -- Igual ao edit original do hornmod -- Fabiano 2020-08-11: é mesmo
{name = "sfx_hbdccr", info = "Churrasqueira Controle Remoto"},
{name = "sfx_hbddib", info = "EU SOU UM DIABO NECESSARIO"},
{name = "sfx_hbdela", info = "Ela Partiu"},
{name = "sfx_hbdgem", info = "Miseravel e um Genio"},
{name = "sfx_hbdpfb", info = "TA PEGANDO FOGO BIXO"},
{name = "sfx_hbdptv", info = "PUTA VIDA"},
{name = "sfx_hbdwoo", info = "VEGETAAA OLHA BEEEEEIM, WOOOOOOOOOOOOOOOOO"},
{name = "sfx_hbdrnd", info = "Ronaldinho Soccer"},
{name = "sfx_hbd7ms", info = "Descobridor dos 7 mares"},
{name = "sfx_hbdbol", info = "Risada do Bola"},
{name = "sfx_hbdcac", info = "Calma Cebolinha"},
{name = "sfx_hbdvdm", info = "Voce deve MORRE"},
{name = "sfx_hbdron", info = "Ronaldo"},
{name = "sfx_hbdqmr", info = "Que merda hein?"},
{name = "sfx_hbdpre", info = "PRERIGO"},
{name = "sfx_hbdmac", info = "OLHA O MACACO"},
{name = "sfx_hbdlcc", info = "Lagartixa com caibra"},
{name = "sfx_hbdjoj", info = "E te JooJ"},
{name = "sfx_hbdflw", info = "Falou - Velberan"},
{name = "sfx_hbdfdp", info = "Teria sido melhor ir ver o filme do Pele"},
{name = "sfx_hbdeuu", info = "EU"},
{name = "sfx_hbdetl", info = "EU NAO TO LOUCO"},
{name = "sfx_hbdete", info = "E TETRA"},
{name = "sfx_hbdczb", info = "Risada do Cazalbe"},
{name = "sfx_hbdcao", info = "Volta o cao arrependido"},
{name = "sfx_hbdbrl", info = "BIRL"},
{name = "sfx_hbdbbn", info = "Ratinho Bobina"},
{name = "sfx_hbdast", info = "Nao contavam com a minha astucia"},
{name = "sfx_hbdaah", info = "AAaaah, eu vo gozaaa"},
{name = "sfx_hbdmud", info = "MUDA MUDA MUDA MUDAAA"},
{name = "sfx_hbdora", info = "ORA ORA ORA ORA ORA ORA ORA ORAA"},
{name = "sfx_hbdtdm", info = "Todo mundo morreu. Acabou"},
{name = "sfx_hbdtfr", info = "VAI QUE E TUA TAFAREL"},
{name = "sfx_hbdtsj", info = "Ta saindo da jaula o monstro"},
{name = "sfx_hbdvaf", info = "Vem afobado assim nao"},
{name = "sfx_hbdvca", info = "VOU CAIR"},
{name = "sfx_hbdvcz", info = "Voce e zoeiro mesmo hein cara"},
{name = "sfx_hbdvnn", info = "Voce nao vale nada"},
{name = "sfx_hbdwtp", info = "WhatsApp"},
{name = "sfx_hbd37a", info = "37 Anos"},
{name = "sfx_hbdabb", info = "Aqui e bodybuilder PORRA"},
{name = "sfx_hbdabq", info = "Achou que eu tava brincando?"},
{name = "sfx_hbdacr", info = "Acerto Mizeravi"},
{name = "sfx_hbdadm", info = "O administrador esta online, pode badernar"},
{name = "sfx_hbdama", info = "Amanco, Amanco"},
{name = "sfx_hbdamk", info = "O amor entre uma mulher e um otaco"},
{name = "sfx_hbdamn", info = "Ameno Ameno"},
{name = "sfx_hbdarn", info = "Arnold Abertura"},
{name = "sfx_hbdatc", info = "Aqui tem coragem"},
{name = "sfx_hbdatu", info = "Risada do peludao (Atumalaca)"},
{name = "sfx_hbdavm", info = "Ah, va a merda porra"},
{name = "sfx_hbdbbb", info = "Baby beibe do biruleibe"},
{name = "sfx_hbdbdd", info = "Bom dia desgraca"},
{name = "sfx_hbdbnk", info = "Bonk - Coquinho"},
{name = "sfx_hbdcab", info = "Cabra gritando"},
{name = "sfx_hbdcaz", info = "Caneta Azul"},
{name = "sfx_hbdccb", info = "Um abraco pro meu tio Cuca Beludo"},
{name = "sfx_hbdceh", info = "Ce eh o bichao mesmo"},
{name = "sfx_hbdcgd", info = "To cagado de fome"},
{name = "sfx_hbdchg", info = "...CHEGA"},
{name = "sfx_hbdcri", info = "Carai Borracha"},
{name = "sfx_hbdctc", info = "Carai tu e cego mizera"},
{name = "sfx_hbdcuz", info = "Eita cuzao"},
{name = "sfx_hbdcvc", info = "Como voce e burro"},
{name = "sfx_hbddad", info = "Dadiva dos ninjas"},
{name = "sfx_hbddy2", info = "Dollyinho seu amiginho"}, -- vamos cantar?
{name = "sfx_hbddjv", info = "Dejavu"},
{name = "sfx_hbddrm", info = "Dorime"},
{name = "sfx_hbddy1", info = "Dolly Guarana Dolly"},
{name = "sfx_hbdegi", info = "Essa gente inventa cada coisa"},
{name = "sfx_hbdemg", info = "E pra matar gente"},
{name = "sfx_hbdenq", info = "Eu nao quero"},
{name = "sfx_hbdepg", info = "Empolgante"},
{name = "sfx_hbdeqd", info = "EU QUERO DORMIR"},
{name = "sfx_hbdesd", info = "Eu sou o Dogras"},
{name = "sfx_hbdetg", info = "Eita Giovana"},
{name = "sfx_hbdeub", info = "Eh uma banana!"},
{name = "sfx_hbdfcj", info = "Follow the damn train CJ"},
{name = "sfx_hbdfhp", info = "Flauta Bugada Harry Potter"},
{name = "sfx_hbdfmb", info = "Funk Mini Boi"},
{name = "sfx_hbdftp", info = "Fui tapeado"},
{name = "sfx_hbdgas", info = "O o gas"},
{name = "sfx_hbdges", info = "Gostam de encher o meu saco"},
{name = "sfx_hbdgjt", info = "Genjutsu desse nivel"},
{name = "sfx_hbdglr", info = "Gloria a Deux"},
{name = "sfx_hbdgrl", info = "Grilos"},
{name = "sfx_hbdhds", info = "HORA DO SHOW"},
{name = "sfx_hbdhjn", info = "Hoje nao, hoje sim"},
{name = "sfx_hbdhwg", info = "Aww shit, here we go again"},
{name = "sfx_hbdibf", info = "I believe I can fly"},
{name = "sfx_hbdill", info = "Illuminati Intro"},
{name = "sfx_hbdinc", info = "Isso non ecziste"},
{name = "sfx_hbdjav", info = "Ja avisei que vai dar merda"},
{name = "sfx_hbdjnn", info = "Joao ninguem"},
{name = "sfx_hbdlhm", info = "La vem o homem macaco"},
{name = "sfx_hbdmdc", info = "Meus deus do ceu Berg"},
{name = "sfx_hbdmdp", info = "Mim de papai"},
{name = "sfx_hbdmmp", info = "Mamilos polemicos"},
{name = "sfx_hbdmna", info = "Meu nome e ari e nao to nem ai"},
{name = "sfx_hbdmpk", info = "Maneiro pra caralho, gostei"},
{name = "sfx_hbdmrr", info = "...E morreu."},
{name = "sfx_hbdnan", info = "NANI"},
{name = "sfx_hbdnct", info = "No ceu tem pao?"},
{name = "sfx_hbdnde", info = "N.Deep - Mano chupa minha pica"},
{name = "sfx_hbdnin", info = "Nao interessa pra voce palhaco"},
{name = "sfx_hbdnit", info = "Nao intendi o que ele falo"},
{name = "sfx_hbdnrt", info = "O Naruto pode ser um pouco duro as vezes"},
{name = "sfx_hbdoh", info = "Knuckles - Oh no"},
{name = "sfx_hbdoi", info = "Oi meu chapa"},
{name = "sfx_hbdomw", info = "Omae wa, mou shindeiru"},
{name = "sfx_hbdoqc", info = "O que, Como"},
{name = "sfx_hbdosl", info = "Olha so, olha la"},
{name = "sfx_hbdpfs", info = "Puta falta de sacanagem"},
{name = "sfx_hbdprb", info = "E quem disse que isso e problema meu"},
{name = "sfx_hbdqbz", info = "Ai que burro da zero pra ele"},
{name = "sfx_hbdqcf", info = "Quero CAFE"},
{name = "sfx_hbdrbt", info = "Ele rebateu de cabeca e foi um lance que"},
{name = "sfx_hbdsbb", info = "Eu so bebo latinha"},
{name = "sfx_hbdsee", info = "Sonic - Estou esperando"},
{name = "sfx_hbdsfd", info = "Se fudeu"},
{name = "sfx_hbdsmj", info = "Sonic - Meu jovem"},
{name = "sfx_hbdste", info = "Steam"},
{name = "sfx_hbdsum", info = "SUMIU"},
{name = "sfx_hbd402", info = "4002-8922", extags = "yudi"},
{name = "sfx_hbdaee", info = "AEE KASINAO"}, -- lendário
{name = "sfx_hbdarr", info = "Arrego"},
{name = "sfx_hbdcgo", info = "CANT GET OVER, VAI DJ!"},
{name = "sfx_hbdcsb", info = "CALA A SUA BOCA"},
{name = "sfx_hbdcvs", info = "Chaves Chorando", extags = "pipipi"},
{name = "sfx_hbdhih", info = "Quico hihihi"},
{name = "sfx_hbdiba", info = "Ibagens com o comandante habilton", extags = "datena"},
{name = "sfx_hbdltc", info = "Lasier tomando choque", extags = "aiaaaaai"}, -- clássico
{name = "sfx_hbdmdc", info = "ME DA MEU CHIP PEDRO"},
{name = "sfx_hbdmer", info = "Fiquei na merda", extags = "Mamonas"},
{name = "sfx_hbdmnp", info = "Dona desse monumental par de coxas", extags = "marcio"},
{name = "sfx_hbdmu1", info = "Isso ai!", extags = "mineirinho"},
{name = "sfx_hbdsbc", info = "E Sabadaco"},
{name = "sfx_hbdsii", info = "Sanduiche-iche", extags = "ruth lemos"},
{name = "sfx_hbdvcb", info = "Vai comecar a baixaria", extags = "mamonas"},
{name = "sfx_hbdvlb", info = "Vira lata sofrendo de bronquite", extags = "quico"},
{name = "sfx_hbdvvp", info = "VOCE E A VERGONHA DA PROFISSION", extags = "pe de fava"},
{name = "sfx_hbdvvm", info = "Eu vim ver o macaco", extags = "Kaiba"}, -- Segundo horn com macaco já
{name = "sfx_hbdbr1", info = "Esse programa aqui ta uma porra"},
{name = "sfx_hbdbr2", info = "Voce destruiu o meu OVO", extags = "Faustao"}, -- You destroyed my egg!
{name = "sfx_hbdbr3", info = "E muito perigoso - Vegeta de Portugal"},
{name = "sfx_hbdbr4", info = "CALMA VIDEL"},
{name = "sfx_hbd0br", info = "Cade o meu uniforme"},
{name = "sfx_hbd1br", info = "Coincidencia, ACHO QUE NAO"},
{name = "sfx_hbd2br", info = "Kachow - Katiau"}, -- relampago marquinhos
{name = "sfx_hbd3br", info = "Caguei nas calcas"},
{name = "sfx_hbd4br", info = "Mogeko - Mogege"},
{name = "sfx_hbd5br", info = "Taca-le pau nesse carrinhos Marcos"},
{name = "sfx_hbd6br", info = "Piss Rocks"},
{name = "sfx_hbd7br", info = "Arveres somos nozes"},
{name = "sfx_hbd8br", info = "Toad Scream"},
{name = "sfx_hbdb0r", info = "Va pro inferno"},
{name = "sfx_hbdb1r", info = "AEEEEEEEEEEEEE"},
{name = "sfx_hbdb2r", info = "HORA DE MORFAR"},
{name = "sfx_hbdb3r", info = "ABRE A TORNEIRA"},
{name = "sfx_hbdb4r", info = "Bravo Bravo Bravissimo"},
{name = "sfx_hbdb5r", info = "Ja chegou o disco voador"},
{name = "sfx_hbdb6r", info = "Prefiro morrer do que perder a vida!"},
{name = "sfx_hbdb7r", info = "Higienicos churros da Dona Florinda"},
{name = "sfx_hbdb8r", info = "TA TA TA TA TA TA TA"},
{name = "sfx_hbdb9r", info = "Ambulancia besta"},
{name = "sfx_hbdbr5", info = "Esse aqui e irmao desse aqui"},
{name = "sfx_hbdbr7", info = "Soda, Limonada, Gostosa e Geladinha"},
{name = "sfx_hbdbr8", info = "E la vamos nos"},
{name = "sfx_hbdbr9", info = "Asas batendo, marcha de decolagem, tubinas e JA!"},
{name = "sfx_hbdbrs", info = "Brasil sil sil"},
{name = "sfx_hbdbrh", info = "Bruh"},
{name = "sfx_hbdnad", info = "Nada que eh do pobre funciona"},
-- horns sumidas daqui pra baixo
{name = "sfx_hbdbr6", info = "Quieto seu quadrupede burro"},
{name = "sfx_hbdhum", info = "Hum, eh mesmo?"},
{name = "sfx_hbdban", info = "BANIDO Ednaldo Pereira"},
{name = "sfx_hbdcvl", info = "Cavalo"},
{name = "sfx_hbdpze", info = "Vai toma no teu cu hein maluco", extags = "MC Poze"},
-- de volta à programação normal
{name = "sfx_hbdbib", info = "Papa Leguas - Bi bi", extags = "meep"},
{name = "sfx_hbdsqu", info = "SQUEAK"}, -- tirar caso for usar o hornmod original dnv eventualmente
-- horns passadas do hell pra cá
{name = "sfx_hbdedj", info = "Ed Junior UOOOOOO", extags = "porra"}, -- desculpa mas eu adoro essa horn
{name = "sfx_hbdhl8", info = "Antonio Nunes"},
{name = "sfx_hbdcng", info = "CORRE NEGADA"},
{name = "sfx_hbdbyt", info = "BLYAAAAAAAAAAAT", extags = "blyat"} -- pedido do rio; só evitar dele cair no random e ta de boa
)


HORNMOD_AddHellHorns({name = "sfx_hbdaaa", info = "MAMAAAAAAAAAAAAAAAAAE"},
{name = "sfx_hbdbar", info = "Seu Barriga Demonio"},
{name = "sfx_hbdbdf", info = "Bau da Felicidade"},
{name = "sfx_hbdkns", info = "KASINAO NO SABADACO"}, -- a musica inteirinha
{name = "sfx_hbdmdj", info = "Sampley de guitarra"},
{name = "sfx_hbdmnp", info = "Dona desse monumental par de coxas", extags = "marcio"},
{name = "sfx_hbdpbt", info = "Pao de batataaa"},
{name = "sfx_hbdplg", info = "Plantao da Globo"},
{name = "sfx_hbdrsr", info = "1 minuto de risadas do Chaves"},
{name = "sfx_hbdsba", info = "Sabao cra cra"},
{name = "sfx_hbdvoa", info = "La vem o alemao - intro"}, -- seila
{name = "sfx_hbdaah", info = "AAaaah, eu vo gozaaa"},
{name = "sfx_hbdhl0", info = "Drake PARKER USANDO A ROUPA DO HOMEM ARANHA"}, -- AAAAAAAAAAAAAAAAA
{name = "sfx_hbdhl1", info = "Trololo Song"},
{name = "sfx_hbdhl2", info = "Ratinho Bobina - Versao Earrape"},
{name = "sfx_hbdhl3", info = "Coloquei um sorriso no rosto..."}, -- C A V A L O
{name = "sfx_hbdhl4", info = "Cavalo rindo"},
{name = "sfx_hbdhl5", info = "VA PRO INFERNO - Versao Earrape"},
{name = "sfx_hbdhl6", info = "Coincidencia? - Versao Earrape"},
{name = "sfx_hbdhl7", info = "Lasier Martins - September Remix"},
{name = "sfx_hbdhl8", info = "Antonio Nunes"},
{name = "sfx_hbdhl9", info = "SENTE A PRESSAO NENEM"},
{name = "sfx_hbdbsb", info = "Bam Bam Saiajeans"},
{name = "sfx_hbdbyt", info = "BLYAAAAAAAAAAAT", extags = "blyat"},
{name = "sfx_hbdcng", info = "CORRE NEGADA"},
{name = "sfx_hbdedj", info = "Ed Junior UOOOOOO", extags = "porra"},
{name = "sfx_hbdesf", info = "Eu sou uma foca"},
{name = "sfx_hbdfff", info = "Fala do meu frifaire"},
{name = "sfx_hbdhsk", info = "Harlem Shake"},
{name = "sfx_hbdiso", info = "Isolados"},
{name = "sfx_hbdjc", info = "JOHN CENA"},
{name = "sfx_hbdess", info = "Essa porra ainda cai"},
{name = "sfx_hbdnss", info = "Nossa vc e muito bom"},
{name = "sfx_hbdppp", info = "N A N I"},
{name = "sfx_hbdvmn", info = "Vai morrer antes do natal"}
)
